### ISSUE TITLE
how to make inferences and predict binding affinity for a given set of structures 

### ISSUE THREAD

**Issue by melyssacheung** [legendzzy/ProAffinity-GNN#2]
hi! i was wondering is there a way i can use the model provided to test on a set of TCR-pMHC complexes? I.e: use the model weights and run inference? (Without retraining the model). If so, could one elaborate how to go about this? Thanks!

**Comment by legendzzy** [comment]
Hi, thank you for your issue, we are going to upload an inference version very soon.

**Comment by melyssacheung** [comment]
thanks! looking fwd to it!

**Comment by legendzzy** [comment]
Hi we have uploaded inference code, please have a check.

**Comment by melyssacheung** [comment]
hi, I checked it out thanks! I'm running into a couple of issues and first just trying it on the example first. I tried going through all the steps, everything is fine up to a certain point; 

command: python ProAffinity_GNN.py 
```
['1a22', '1a3b', '1a4y', '1ahw']
data/graph/inter_graph/1a22
data/graph/inter_graph/1a3b
data/graph/inter_graph/1a4y
data/graph/inter_graph/1ahw
/home/cheungm/proaffinity/lib/python3.9/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
/home/cheungm/.local/lib/python3.9/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Epoch: 1, Train Loss: 150.103, Validation Loss: 59.783
Epoch: 2, Train Loss: 51.161, Validation Loss: 25.972
Epoch: 3, Train Loss: 29.170, Validation Loss: 17.187
Epoch: 4, Train Loss: 7.301, Validation Loss: 13.953
Epoch: 5, Train Loss: 18.010, Validation Loss: 18.404
Epoch: 6, Train Loss: 10.122, Validation Loss: 28.904
Epoch: 7, Train Loss: 6.517, Validation Loss: 37.696
Epoch: 8, Train Loss: 20.005, Validation Loss: 38.508
Epoch: 9, Train Loss: 3.513, Validation Loss: 35.823
Epoch: 10, Train Loss: 3.611, Validation Loss: 29.904
Epoch: 11, Train Loss: 25.610, Validation Loss: 32.327
Epoch: 12, Train Loss: 5.155, Validation Loss: 32.060
Epoch: 13, Train Loss: 4.314, Validation Loss: 31.361
Epoch: 14, Train Loss: 1.860, Validation Loss: 32.185
Stopping early at epoch 14
/home/cheungm/ProAffinity-GNN/ProAffinity_GNN.py:223: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(model_save))
/home/cheungm/.local/lib/python3.9/site-packages/torch/nn/modules/loss.py:128: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
L1 Test Loss: 3.735
Ref Test Loss: 5.095
1
/home/cheungm/proaffinity/lib/python3.9/site-packages/numpy/lib/_function_base_impl.py:2914: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/home/cheungm/proaffinity/lib/python3.9/site-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/home/cheungm/proaffinity/lib/python3.9/site-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
Pearson Correlation Coefficient: nan
cuda
4
0
4
0
4
0
Traceback (most recent call last):
  File "/home/cheungm/ProAffinity-GNN/ProAffinity_GNN.py", line 378, in <module>
    val_loss = evaluate(model, val_loader_inter, val_loader_intra1, val_loader_intra2, criterion=criterion)
  File "/home/cheungm/ProAffinity-GNN/ProAffinity_GNN.py", line 156, in evaluate
    return total_loss / len(data_loader_inter.dataset)
ZeroDivisionError: division by zero
```

When I try, 
command: python ProAffinity-GNN_inference.py -f 1ak4_processed.pdbqt -c A,D 

python ProAffinity-GNN_inference.py -f 1ak4_processed.pdbqt -c A,D
['A', 'D']
Some weights of EsmModel were not initialized from the model checkpoint at facebook/esm2_t33_650M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/cheungm/ProAffinity-GNN/ProAffinity-GNN_inference/ProAffinity-GNN_inference.py:873: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('./model.pkl'))
Traceback (most recent call last):
  File "/home/cheungm/ProAffinity-GNN/ProAffinity-GNN_inference/ProAffinity-GNN_inference.py", line 873, in <module>
    model.load_state_dict(torch.load('./model.pkl'))
  File "/home/cheungm/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for GraphNetwork:
	Missing key(s) in state_dict: "graph1.model.atom_convs.0.lin.weight", "graph1.model.atom_convs.1.lin.weight", "graph1.model.mol_conv.lin.weight", "graph2.model.atom_convs.0.lin.weight", "graph2.model.atom_convs.1.lin.weight", "graph2.model.mol_conv.lin.weight", "graph3.model.atom_convs.0.lin.weight", "graph3.model.atom_convs.1.lin.weight", "graph3.model.mol_conv.lin.weight". 
	Unexpected key(s) in state_dict: "graph1.model.atom_convs.0.lin_src.weight", "graph1.model.atom_convs.0.lin_dst.weight", "graph1.model.atom_convs.1.lin_src.weight", "graph1.model.atom_convs.1.lin_dst.weight", "graph1.model.mol_conv.lin_src.weight", "graph1.model.mol_conv.lin_dst.weight", "graph2.model.atom_convs.0.lin_src.weight", "graph2.model.atom_convs.0.lin_dst.weight", "graph2.model.atom_convs.1.lin_src.weight", "graph2.model.atom_convs.1.lin_dst.weight", "graph2.model.mol_conv.lin_src.weight", "graph2.model.mol_conv.lin_dst.weight", "graph3.model.atom_convs.0.lin_src.weight", "graph3.model.atom_convs.0.lin_dst.weight", "graph3.model.atom_convs.1.lin_src.weight", "graph3.model.atom_convs.1.lin_dst.weight", "graph3.model.mol_conv.lin_src.weight", "graph3.model.mol_conv.lin_dst.weight".
	
What's the best way to go about these problems? Thanks!

**Comment by legendzzy** [comment]
It should be due to the issue of torch_geometric version. Please see the readme file and use the version of 2.3.

**Comment by melyssacheung** [comment]
i actually have that installed, heres the output when i print out the versions i have that seem to match your read me 
```
python -c "import torch_geometric; print('PyTorch-Geometric:', torch_geometric.__version__)"
PyTorch-Geometric: 2.3.0
(ProAffinity) [cheungm@cluster-pierce ProAffinity-GNN]$ python -c "import transformers; print('Transformers:', transformers.__version__)"
Transformers: 4.38.0
(ProAffinity) [cheungm@cluster-pierce ProAffinity-GNN]$ python -c "import sklearn; print('Scikit-Learn:', sklearn.__version__)"
Scikit-Learn: 1.3.2
(ProAffinity) [cheungm@cluster-pierce ProAffinity-GNN]$ python -c "import sys; print('Python:', sys.version)"
Python: 3.8.20 | packaged by conda-forge | (default, Sep 30 2024, 17:52:49) 
[GCC 13.3.0]
python -c "import torch; print('PyTorch:', torch.__version__)"
PyTorch: 2.2.2
```

I double checked and reran but still having the same issues with the examples alone

**Comment by legendzzy** [comment]
You can try using our uploaded environment file. This error should be the problem of torch-geometric, you can refer to other issue that shares the same problem here.

**Comment by melyssacheung** [comment]
I'm not sure whats going on but despite using the provided .yaml file, im still running into the same issue

additionally, I ran the inference script -- is the pka the only expected output? (using the example only)

**Comment by legendzzy** [comment]
Yes the Pka is the only predicted value. As for the issue, sorry to hear that, maybe it is supposed to double-check the environment. I saw that you have run the inference, if it was successful, it meant the environment is OK.
